const STATIC_HEADERS={
  'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY',
  'Referrer-Policy':'strict-origin-when-cross-origin',
  'Permissions-Policy':'camera=(), microphone=(), geolocation=()'
};
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...STATIC_HEADERS,...extra}});
const text=(s,status=200,extra={})=>new Response(s,{status,headers:{'Content-Type':'text/plain; charset=utf-8',...STATIC_HEADERS,...extra}});
const now=()=>new Date().toISOString();
const uuid=()=>crypto.randomUUID();
async function body(req){const t=await req.text(); if(!t)return{}; try{return JSON.parse(t)}catch{return null}}
function cookies(req){const o={};for(const p of (req.headers.get('Cookie')||'').split(';')){const i=p.indexOf('=');if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1))}return o}
function cookie(name,val,maxAge){return `${name}=${encodeURIComponent(val)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}`}
async function digestHex(buf){return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function hashPassword(password,salt){const enc=new TextEncoder();const key=await crypto.subtle.importKey('raw',enc.encode(password),{name:'PBKDF2'},false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:100000,hash:'SHA-256'},key,256);return digestHex(bits)}
async function newPassword(password){const salt=uuid();return `${salt}:${await hashPassword(password,salt)}`}
async function verifyPassword(password,stored){const [salt,hash]=String(stored||'').split(':');if(!salt||!hash)return false;return (await hashPassword(password,salt))===hash}
function safeUser(u){return u&&{id:u.id,name:u.name,email:u.email,role:u.role,createdAt:u.created_at||u.createdAt}}
async function ensureSchema(db){await db.batch([
  db.prepare(`CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, data TEXT NOT NULL)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'customer', created_at TEXT NOT NULL)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_id TEXT NOT NULL, expires_at INTEGER NOT NULL)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS carts (user_id TEXT PRIMARY KEY, data TEXT NOT NULL)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS addresses (user_id TEXT PRIMARY KEY, data TEXT NOT NULL)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, data TEXT NOT NULL, created_at TEXT NOT NULL)`)
]);
  const count=await db.prepare('SELECT COUNT(*) AS c FROM products').first('c');
  if(!Number(count)){
    const products=[
      {id:'aero-jacket',name:'AERO JACKET',code:'AERO 001',category:'JACKETS',price:6990,compareAt:7990,description:'Lightweight windproof outerwear engineered for movement.',materials:'Aero-shell nylon, technical mesh lining',colors:['Obsidian Black','Performance Red','Arctic White'],sizes:['S','M','L','XL'],badge:'BESTSELLER',stock:24,active:true,featured:true},
      {id:'struct-hoodie',name:'STRUCT HOODIE',code:'STRUCT 002',category:'HOODIES',price:4990,compareAt:null,description:'Structured heavyweight hoodie with engineered paneling.',materials:'Premium cotton fleece, bonded rib',colors:['Obsidian Black','Titanium'],sizes:['S','M','L','XL'],stock:31,active:true,featured:true},
      {id:'velocity-tee',name:'VELOCITY TEE',code:'VELOCITY 003',category:'SHIRTS',price:2490,compareAt:null,description:'Performance jersey tee with a clean aerodynamic silhouette.',materials:'Technical stretch jersey',colors:['Obsidian Black','Arctic White','Performance Red'],sizes:['S','M','L','XL'],stock:46,active:true,featured:false},
      {id:'titan-pants',name:'TITAN PANTS',code:'TITAN 004',category:'PANTS',price:4990,compareAt:null,description:'Tapered utility trousers built for daily motion.',materials:'Stretch technical twill',colors:['Obsidian Black','Graphite'],sizes:['S','M','L','XL'],stock:18,active:true,featured:true}
    ];
    for(const p of products)await db.prepare('INSERT INTO products(id,data) VALUES(?,?)').bind(p.id,JSON.stringify(p)).run();
  }
  const adminEmail=(envAdminEmail(db) || 'admin@resemble.local').toLowerCase();
  const admin=await db.prepare('SELECT id FROM users WHERE email=?').bind(adminEmail).first();
  if(!admin){const hp=await newPassword(envAdminPassword(db)||'ResembleAdmin123!');await db.prepare('INSERT INTO users(id,name,email,password_hash,role,created_at) VALUES(?,?,?,?,?,?)').bind('RS-ADMIN','RESEMBLE ADMIN',adminEmail,hp,'admin',now()).run();}
}
// Environment access helpers intentionally read from global env proxy set in fetch.
let ENV=null; function envAdminEmail(){return ENV?.RESEMBLE_ADMIN_EMAIL||''} function envAdminPassword(){return ENV?.RESEMBLE_ADMIN_PASSWORD||''}
async function currentUser(req,db){const t=cookies(req).resemble_session;if(!t)return null;const s=await db.prepare('SELECT * FROM sessions WHERE token=?').bind(t).first();if(!s)return null;if(Number(s.expires_at)<Date.now()){await db.prepare('DELETE FROM sessions WHERE token=?').bind(t).run();return null}return await db.prepare('SELECT * FROM users WHERE id=?').bind(s.user_id).first()}
async function requireUser(req,db){return currentUser(req,db)}
async function loginSession(user,db){const token=crypto.randomUUID()+crypto.randomUUID();await db.prepare('INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)').bind(token,user.id,Date.now()+1209600000).run();return token}
function productFromRow(r){return JSON.parse(r.data)}
async function getProduct(db,id){const r=await db.prepare('SELECT data FROM products WHERE id=?').bind(id).first();return r?productFromRow(r):null}
async function allProducts(db){const r=await db.prepare('SELECT data FROM products').all();return (r.results||[]).map(productFromRow)}
function validateItems(items,products){const out=[];for(const x of Array.isArray(items)?items:[]){const p=products.find(z=>z.id===String(x.id));if(!p||p.active===false)continue;const size=String(x.size||'M');const color=String(x.color||(p.colors||[])[0]||'');if(!(p.sizes||[]).includes(size)||(p.colors||[]).length&&!p.colors.includes(color))continue;const qty=Math.max(1,Math.min(99,Number(x.qty||1)));out.push({lineId:`${p.id}__${size}__${color}`,id:p.id,name:p.name,price:Number(p.price),size,color,qty});}return out}
function totals(items){const subtotal=items.reduce((n,x)=>n+x.price*x.qty,0),shipping=subtotal>=5000?0:199;return{subtotal,shipping,total:subtotal+shipping}}
async function razorpay(path,method,payload,env){const id=env.RAZORPAY_KEY_ID||'',secret=env.RAZORPAY_KEY_SECRET||'';if(!id||!secret)throw new Error('RAZORPAY_KEYS_MISSING');const h=btoa(`${id}:${secret}`);const r=await fetch(`https://api.razorpay.com/v1${path}`,{method,headers:{Authorization:`Basic ${h}`,'Content-Type':'application/json'},body:payload?JSON.stringify(payload):undefined});const d=await r.json();if(!r.ok)throw new Error(d?.error?.description||'RAZORPAY_ERROR');return d}
async function hmacHex(value,secret){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return digestHex(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(value)))}
async function handleApi(req,url,env){const db=env.DB;if(!db)return json({ok:false,error:'D1_NOT_BOUND'},500);ENV=env;await ensureSchema(db);
  const p=url.pathname,m=req.method;
  if(m==='GET'&&p==='/api/health')return json({ok:true,service:'RESEMBLE CLOUDFLARE WORKER',time:now(),db:'d1',paymentMode:String(env.PAYMENT_MODE||'demo')});
  if(m==='GET'&&p==='/api/products')return json({ok:true,products:await allProducts(db)});
  if(m==='GET'&&p.startsWith('/api/products/')){const x=await getProduct(db,decodeURIComponent(p.split('/').pop()));return x?json({ok:true,product:x}):json({ok:false,error:'PRODUCT_NOT_FOUND'},404)}
  if(p==='/api/auth/signup'&&m==='POST'){const b=await body(req)||{};const name=String(b.name||'').trim(),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');if(name.length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<8)return json({ok:false,error:'INVALID_SIGNUP'},400);if(await db.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return json({ok:false,error:'ACCOUNT_EXISTS'},400);const u={id:'RS-'+crypto.randomUUID().slice(0,8).toUpperCase(),name,email,created_at:now(),role:'customer'};await db.prepare('INSERT INTO users(id,name,email,password_hash,role,created_at) VALUES(?,?,?,?,?,?)').bind(u.id,u.name,u.email,await newPassword(password),u.role,u.created_at).run();const t=await loginSession(u,db);return json({ok:true,user:safeUser(u)},{status:201,headers:{'Set-Cookie':cookie('resemble_session',t,1209600)}})}
  if(p==='/api/auth/login'&&m==='POST'){const b=await body(req)||{};const u=await db.prepare('SELECT * FROM users WHERE email=?').bind(String(b.email||'').trim().toLowerCase()).first();if(!u||!(await verifyPassword(String(b.password||''),u.password_hash)))return json({ok:false,error:'INVALID_CREDENTIALS'},401);const t=await loginSession(u,db);return json({ok:true,user:safeUser(u)},{headers:{'Set-Cookie':cookie('resemble_session',t,1209600)}})}
  if(p==='/api/auth/me'&&m==='GET'){const u=await currentUser(req,db);return json({ok:true,user:safeUser(u)})}
  if(p==='/api/auth/logout'&&m==='POST'){const t=cookies(req).resemble_session;if(t)await db.prepare('DELETE FROM sessions WHERE token=?').bind(t).run();return json({ok:true},{headers:{'Set-Cookie':cookie('resemble_session','',0)}})}
  const user=await currentUser(req,db);
  if(p==='/api/account/profile'&&m==='PUT'){if(!user)return json({ok:false,error:'AUTH_REQUIRED'},401);const b=await body(req)||{};const name=String(b.name||user.name).trim();await db.prepare('UPDATE users SET name=? WHERE id=?').bind(name,user.id).run();const u=await db.prepare('SELECT * FROM users WHERE id=?').bind(user.id).first();return json({ok:true,user:safeUser(u)})}
  if(p==='/api/cart'&&m==='GET'){if(!user)return json({ok:true,items:[]});const r=await db.prepare('SELECT data FROM carts WHERE user_id=?').bind(user.id).first();return json({ok:true,items:r?JSON.parse(r.data):[]})}
  if(p==='/api/cart'&&m==='PUT'){if(!user)return json({ok:false,error:'AUTH_REQUIRED'},401);const b=await body(req)||{};const items=validateItems(b.items||[],await allProducts(db));await db.prepare('INSERT INTO carts(user_id,data) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET data=excluded.data').bind(user.id,JSON.stringify(items)).run();return json({ok:true,items})}
  if(p==='/api/cart'&&m==='DELETE'){if(!user)return json({ok:false,error:'AUTH_REQUIRED'},401);await db.prepare('DELETE FROM carts WHERE user_id=?').bind(user.id).run();return json({ok:true})}
  if(p==='/api/addresses'&&m==='GET'){if(!user)return json({ok:true,addresses:[]});const r=await db.prepare('SELECT data FROM addresses WHERE user_id=?').bind(user.id).first();return json({ok:true,addresses:r?JSON.parse(r.data):[]})}
  if(p==='/api/addresses'&&m==='PUT'){if(!user)return json({ok:false,error:'AUTH_REQUIRED'},401);const b=await body(req)||{};await db.prepare('INSERT INTO addresses(user_id,data) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET data=excluded.data').bind(user.id,JSON.stringify(Array.isArray(b.addresses)?b.addresses:[])).run();return json({ok:true,addresses:b.addresses||[]})}
  if(p==='/api/orders'&&m==='GET'){if(!user)return json({ok:true,orders:[]});const r=await db.prepare('SELECT data FROM orders WHERE user_id=? ORDER BY created_at DESC').bind(user.id).all();return json({ok:true,orders:(r.results||[]).map(x=>JSON.parse(x.data))})}
  if(p==='/api/orders'&&m==='POST'){if(!user)return json({ok:false,error:'AUTH_REQUIRED'},401);const b=await body(req)||{};const products=await allProducts(db),items=validateItems(b.items||[],products);if(!items.length)return json({ok:false,error:'EMPTY_ORDER'},400);for(const x of items){const p=products.find(z=>z.id===x.id);if(Number(p.stock)<x.qty)return json({ok:false,error:`OUT_OF_STOCK_${x.id}`},400)}const t=totals(items),order={id:uuid(),number:'RSB#'+Math.floor(10000+Math.random()*90000),userId:user.id,status:'Processing',items,shippingAddress:b.shippingAddress||{},shippingFee:t.shipping,subtotal:t.subtotal,total:t.total,payment:b.payment||{},createdAt:now()};for(const x of items){const p=products.find(z=>z.id===x.id);p.stock=Number(p.stock)-x.qty;await db.prepare('UPDATE products SET data=? WHERE id=?').bind(JSON.stringify(p),p.id).run()}await db.prepare('INSERT INTO orders(id,user_id,data,created_at) VALUES(?,?,?,?)').bind(order.id,user.id,JSON.stringify(order),order.createdAt).run();await db.prepare('DELETE FROM carts WHERE user_id=?').bind(user.id).run();return json({ok:true,order},{status:201})}
  if(p==='/api/payment/create'&&m==='POST'){if(!user)return json({ok:false,error:'AUTH_REQUIRED'},401);const b=await body(req)||{};const amount=Math.round(Number(b.amount||0)*100),mode=String(env.PAYMENT_MODE||'demo').toLowerCase();if(amount<=0)return json({ok:false,error:'INVALID_AMOUNT'},400);if(mode!=='live')return json({ok:true,payment:{mode:'demo',provider:env.PAYMENT_PROVIDER||'Razorpay',amount:amount/100,currency:'INR',name:'RESEMBLE',status:'authorized-demo',method:b.method||'CARD'}});try{const rp=await razorpay('/orders','POST',{amount,currency:'INR',receipt:`resemble_${Date.now()}`},env);return json({ok:true,payment:{mode:'live',provider:'Razorpay',amount,currency:'INR',keyId:env.RAZORPAY_KEY_ID,razorpayOrderId:rp.id,name:'RESEMBLE',description:'RESEMBLE ORDER'}})}catch(e){return json({ok:false,error:e.message},502)}}
  if(p==='/api/payment/verify'&&m==='POST'){if(!user)return json({ok:false,error:'AUTH_REQUIRED'},401);const b=await body(req)||{};if(String(env.PAYMENT_MODE||'demo').toLowerCase()!=='live')return json({ok:true,payment:{mode:'demo',status:'authorized-demo',...b}});if(!b.razorpay_order_id||!b.razorpay_payment_id||!b.razorpay_signature)return json({ok:false,error:'PAYMENT_DATA_MISSING'},400);const expected=await hmacHex(`${b.razorpay_order_id}|${b.razorpay_payment_id}`,env.RAZORPAY_KEY_SECRET);if(expected!==b.razorpay_signature)return json({ok:false,error:'PAYMENT_SIGNATURE_INVALID'},400);return json({ok:true,payment:{mode:'live',provider:'Razorpay',status:'captured',...b}})}
  if(p==='/api/payment/webhook'&&m==='POST'){const raw=await req.text(),sig=req.headers.get('x-razorpay-signature')||'';if(!env.RAZORPAY_WEBHOOK_SECRET)return text('webhook secret not configured',503);const expected=await hmacHex(raw,env.RAZORPAY_WEBHOOK_SECRET);if(expected!==sig)return text('invalid signature',400);return json({ok:true})}
  if(p==='/api/admin/stats'&&m==='GET'){if(!user||user.role!=='admin')return json({ok:false,error:'ADMIN_REQUIRED'},403);const products=await allProducts(db),rc=await db.prepare('SELECT COUNT(*) c FROM orders').first('c'),uc=await db.prepare("SELECT COUNT(*) c FROM users WHERE role='customer'").first('c'),orders=await db.prepare('SELECT data FROM orders').all();const list=(orders.results||[]).map(x=>JSON.parse(x.data));return json({ok:true,stats:{products:products.length,lowStock:products.filter(x=>Number(x.stock)<=5).length,orders:Number(rc||0),customers:Number(uc||0),revenue:list.reduce((n,o)=>n+Number(o.total||0),0)}})}
  if(p==='/api/admin/orders'&&m==='GET'){if(!user||user.role!=='admin')return json({ok:false,error:'ADMIN_REQUIRED'},403);const r=await db.prepare('SELECT data FROM orders ORDER BY created_at DESC').all();return json({ok:true,orders:(r.results||[]).map(x=>JSON.parse(x.data))})}
  if(p.startsWith('/api/admin/orders/')&&m==='PUT'){if(!user||user.role!=='admin')return json({ok:false,error:'ADMIN_REQUIRED'},403);const id=decodeURIComponent(p.split('/').pop()),b=await body(req)||{},r=await db.prepare('SELECT data FROM orders WHERE id=?').bind(id).first();if(!r)return json({ok:false,error:'ORDER_NOT_FOUND'},404);const o=JSON.parse(r.data);o.status=String(b.status||o.status);await db.prepare('UPDATE orders SET data=? WHERE id=?').bind(JSON.stringify(o),id).run();return json({ok:true,order:o})}
  if(p==='/api/admin/users'&&m==='GET'){if(!user||user.role!=='admin')return json({ok:false,error:'ADMIN_REQUIRED'},403);const r=await db.prepare("SELECT id,name,email,role,created_at FROM users ORDER BY created_at DESC").all();return json({ok:true,users:(r.results||[]).map(safeUser)})}
  if(p==='/api/admin/products'&&m==='POST'&&user?.role==='admin'){const b=await body(req)||{};const id=String(b.id||uuid());const pdt={...b,id,price:Number(b.price||0),stock:Number(b.stock||0),active:b.active!==false,featured:!!b.featured};await db.prepare('INSERT INTO products(id,data) VALUES(?,?)').bind(id,JSON.stringify(pdt)).run();return json({ok:true,product:pdt},{status:201})}
  if(p.startsWith('/api/products/')&&m==='PUT'&&user?.role==='admin'){const id=decodeURIComponent(p.split('/').pop()),old=await getProduct(db,id);if(!old)return json({ok:false,error:'PRODUCT_NOT_FOUND'},404);const b=await body(req)||{},pdt={...old,...b,id,price:Number(b.price??old.price),stock:Number(b.stock??old.stock),active:b.active!==false};await db.prepare('UPDATE products SET data=? WHERE id=?').bind(JSON.stringify(pdt),id).run();return json({ok:true,product:pdt})}
  if(p.startsWith('/api/products/')&&m==='DELETE'&&user?.role==='admin'){const id=decodeURIComponent(p.split('/').pop());await db.prepare('DELETE FROM products WHERE id=?').bind(id).run();return json({ok:true})}
  return json({ok:false,error:'NOT_FOUND'},404)
}
export default {async fetch(req,env){try{const url=new URL(req.url);if(url.pathname.startsWith('/api/'))return await handleApi(req,url,env);const r=await env.ASSETS.fetch(req);if(r.status!==404)return r;return await env.ASSETS.fetch(new Request(new URL('/index.html',req.url),req));}catch(e){console.error(e);return json({ok:false,error:'SERVER_ERROR',detail:String(e.message||e)},500)}}}
