name = "resemble"
main = "worker.js"
compatibility_date = "2026-09-03"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "resemble-db"
database_id = "ef6305db-ead3-46aa-ae3c-00a5885d0ca6"

[vars]
PAYMENT_MODE = "demo"
PAYMENT_PROVIDER = "Razorpay"
RESEMBLE_ADMIN_EMAIL = "admin@resemble.local"
RESEMBLE_ADMIN_PASSWORD = "J@shua32007@934671"
